# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a0019b19fe0332100ae08598c2a34323147209e602107599499da00dc59335bffedf1faae04313f571da2dad8390f5167598525a803a9908fbe81bc6e1f7930

test:
  secret_key_base: 6a7e3bcef2d0ed781558f8a37411086b49b0cb260346f70e3fce49805cee64f02eb16a6c900f0a4d2e3feea5705e4b2c8f4dc9dbe8dfc3036b4226fc24da9de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
